apiVersion: v2
name: sd-reward-points-account
description: "BIAN Service Domain: Reward Points Account (Fulfill pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - fulfill
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Account Management"
  bian/asset-type: "Reward Points Facility"
  bian/control-record: "Reward Points Facility Fulfillment Arrangement"
